version: "3.9"

services:
  app:
    build:
      context: server
      args:
        - DEV=true
    ports:
      - "8000:8000"
    networks:
      - node-network
    volumes:
      - ./server/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  react-front-end:
    build:
      context: client
    container_name: react-front-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5173:5173"
    command: npm run dev

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    networks:
      - node-network

volumes:
  dev-db-data:

networks:
  node-network:
    driver: bridge
